name: Container_Build
on:
  push:
    branches:
      - master
    paths:
      - 'dockerfile'
      - 'Makefile'
      -'.github/workflows/**'
jobs:
  Container_Build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }} 
      IMAGE_NAME : "weather-app-samrdaymond"
      REGION : "ap-southeast-2"
      REPO_NAME : "samrdaymond-weather-app" 
    steps:
    - uses: actions/checkout@v2
    - name: Container_Build
      run: make docker_push_image       




